services:
  employee-db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=employee_db
      - POSTGRES_USER=employee
      - POSTGRES_PASSWORD=employee
    ports:
      - "5434:5432"
    volumes:
      - employee-db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  employee-db-data: