services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=vacation_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - '5432'
