services:
  admin-db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=admin_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5433:5432"
    volumes:
      - admin-db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  admin-db-data: